# netlify.toml
[build]
  publish = "client/dist"  # Where your Vite/React build lives
  command = "npm run build"

[[redirects]]
  from = "/api/*"
  to = "https://cpsc-362-brite-daniel-gilbert.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  # This handles the React Router "Page Not Found" refresh error
  from = "/*"
  to = "/index.html"
  status = 200